/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { MediaEncoding_Codecs_Common_Types_BitRate } from './MediaEncoding_Codecs_Common_Types_BitRate';
import type { MediaEncoding_Codecs_Common_Types_ProfileLevelInformation } from './MediaEncoding_Codecs_Common_Types_ProfileLevelInformation';
export type MediaEncoding_Codecs_VideoCodecs_VideoCodecBase = {
    CodecKind?: MediaEncoding_Codecs_VideoCodecs_VideoCodecBase.CodecKind;
    MediaTypeName?: string;
    VideoMediaType?: MediaEncoding_Codecs_VideoCodecs_VideoCodecBase.VideoMediaType;
    MinWidth?: number | null;
    MaxWidth?: number | null;
    MinHeight?: number | null;
    MaxHeight?: number | null;
    WidthAlignment?: number | null;
    HeightAlignment?: number | null;
    MinFrameRate?: number | null;
    MaxFrameRate?: number | null;
    SupportedColorFormats?: Array<'Unknown' | 'yuv420p' | 'yuyv422' | 'rgb24' | 'bgr24' | 'yuv422p' | 'yuv444p' | 'yuv410p' | 'yuv411p' | 'gray' | 'monow' | 'monob' | 'pal8' | 'yuvj420p' | 'yuvj422p' | 'yuvj444p' | 'uyvy422' | 'uyyvyy411' | 'bgr8' | 'bgr4' | 'bgr4_byte' | 'rgb8' | 'rgb4' | 'rgb4_byte' | 'nv12' | 'nv21' | 'argb' | 'rgba' | 'abgr' | 'bgra' | 'gray16' | 'yuv440p' | 'yuvj440p' | 'yuva420p' | 'rgb48' | 'rgb565' | 'rgb555' | 'bgr565' | 'bgr555' | 'vaapi_moco' | 'vaapi_idct' | 'vaapi_vld' | 'yuv420p16' | 'yuv422p16' | 'yuv444p16' | 'dxva2_vld' | 'rgb444' | 'bgr444' | 'ya8' | 'bgr48' | 'yuv420p9' | 'yuv420p10' | 'yuv422p10' | 'yuv444p9' | 'yuv444p10' | 'yuv422p9' | 'gbrp' | 'gbrp9' | 'gbrp10' | 'gbrp16' | 'yuva422p' | 'yuva444p' | 'yuva420p9' | 'yuva422p9' | 'yuva444p9' | 'yuva420p10' | 'yuva422p10' | 'yuva444p10' | 'yuva420p16' | 'yuva422p16' | 'yuva444p16' | 'vdpau' | 'xyz12' | 'nv16' | 'nv20' | 'rgba64' | 'bgra64' | 'yvyu422' | 'ya16' | 'gbrap' | 'gbrap16' | 'qsv' | 'mmal' | 'd3d11va_vld' | 'cuda' | '_0rgb' | 'rgb0' | '_0bgr' | 'bgr0' | 'yuv420p12' | 'yuv420p14' | 'yuv422p12' | 'yuv422p14' | 'yuv444p12' | 'yuv444p14' | 'gbrp12' | 'gbrp14' | 'yuvj411p' | 'bayer_bggr8' | 'bayer_rggb8' | 'bayer_gbrg8' | 'bayer_grbg8' | 'bayer_bggr16' | 'bayer_rggb16' | 'bayer_gbrg16' | 'bayer_grbg16' | 'xvmc' | 'yuv440p10' | 'yuv440p12' | 'ayuv64' | 'videotoolbox_vld' | 'p010' | 'gbrap12' | 'gbrap10' | 'mediacodec' | 'gray12' | 'gray10' | 'p016' | 'd3d11' | 'gray9' | 'gbrpf32' | 'gbrapf32' | 'drm_prime' | 'opencl'>;
    SupportedColorFormatStrings?: Array<string>;
    ProfileAndLevelInformation?: Array<MediaEncoding_Codecs_Common_Types_ProfileLevelInformation>;
    Id?: string;
    Direction?: MediaEncoding_Codecs_VideoCodecs_VideoCodecBase.Direction;
    Name?: string;
    Description?: string;
    FrameworkCodec?: string;
    IsHardwareCodec?: boolean;
    SecondaryFramework?: MediaEncoding_Codecs_VideoCodecs_VideoCodecBase.SecondaryFramework;
    SecondaryFrameworkCodec?: string;
    MaxInstanceCount?: number | null;
    MinBitRate?: MediaEncoding_Codecs_Common_Types_BitRate;
    MaxBitRate?: MediaEncoding_Codecs_Common_Types_BitRate;
    IsEnabledByDefault?: boolean;
    DefaultPriority?: number;
};
export namespace MediaEncoding_Codecs_VideoCodecs_VideoCodecBase {
    export enum CodecKind {
        AUDIO = 'Audio',
        VIDEO = 'Video',
        SUB_TITLES = 'SubTitles',
    }
    export enum VideoMediaType {
        UNKNOWN = 'Unknown',
        COPY = 'copy',
        FLV1 = 'flv1',
        H263 = 'h263',
        H263P = 'h263p',
        H264 = 'h264',
        HEVC = 'hevc',
        MJPEG = 'mjpeg',
        MPEG1VIDEO = 'mpeg1video',
        MPEG2VIDEO = 'mpeg2video',
        MPEG4 = 'mpeg4',
        MSVIDEO1 = 'msvideo1',
        THEORA = 'theora',
        VC1IMAGE = 'vc1image',
        VC1 = 'vc1',
        VP8 = 'vp8',
        VP9 = 'vp9',
        WMV1 = 'wmv1',
        WMV2 = 'wmv2',
        WMV3 = 'wmv3',
        _012V = '_012v',
        _4XM = '_4xm',
        _8BPS = '_8bps',
        A64_MULTI = 'a64_multi',
        A64_MULTI5 = 'a64_multi5',
        AASC = 'aasc',
        AIC = 'aic',
        ALIAS_PIX = 'alias_pix',
        AMV = 'amv',
        ANM = 'anm',
        ANSI = 'ansi',
        APNG = 'apng',
        ASV1 = 'asv1',
        ASV2 = 'asv2',
        AURA = 'aura',
        AURA2 = 'aura2',
        AV1 = 'av1',
        AVRN = 'avrn',
        AVRP = 'avrp',
        AVS = 'avs',
        AVUI = 'avui',
        AYUV = 'ayuv',
        BETHSOFTVID = 'bethsoftvid',
        BFI = 'bfi',
        BINKVIDEO = 'binkvideo',
        BINTEXT = 'bintext',
        BITPACKED = 'bitpacked',
        BMP = 'bmp',
        BMV_VIDEO = 'bmv_video',
        BRENDER_PIX = 'brender_pix',
        C93 = 'c93',
        CAVS = 'cavs',
        CDGRAPHICS = 'cdgraphics',
        CDXL = 'cdxl',
        CFHD = 'cfhd',
        CINEPAK = 'cinepak',
        CLEARVIDEO = 'clearvideo',
        CLJR = 'cljr',
        CLLC = 'cllc',
        CMV = 'cmv',
        CPIA = 'cpia',
        CSCD = 'cscd',
        CYUV = 'cyuv',
        DAALA = 'daala',
        DDS = 'dds',
        DFA = 'dfa',
        DIRAC = 'dirac',
        DNXHD = 'dnxhd',
        DPX = 'dpx',
        DSICINVIDEO = 'dsicinvideo',
        DVVIDEO = 'dvvideo',
        DXA = 'dxa',
        DXTORY = 'dxtory',
        DXV = 'dxv',
        ESCAPE124 = 'escape124',
        ESCAPE130 = 'escape130',
        EXR = 'exr',
        FFV1 = 'ffv1',
        FFVHUFF = 'ffvhuff',
        FIC = 'fic',
        FITS = 'fits',
        FLASHSV = 'flashsv',
        FLASHSV2 = 'flashsv2',
        FLIC = 'flic',
        FMVC = 'fmvc',
        FRAPS = 'fraps',
        FRWU = 'frwu',
        G2M = 'g2m',
        GDV = 'gdv',
        GIF = 'gif',
        H261 = 'h261',
        H263I = 'h263i',
        HAP = 'hap',
        HNM4VIDEO = 'hnm4video',
        HQ_HQA = 'hq_hqa',
        HQX = 'hqx',
        HUFFYUV = 'huffyuv',
        IDCIN = 'idcin',
        IDF = 'idf',
        IFF_ILBM = 'iff_ilbm',
        INDEO2 = 'indeo2',
        INDEO3 = 'indeo3',
        INDEO4 = 'indeo4',
        INDEO5 = 'indeo5',
        INTERPLAYVIDEO = 'interplayvideo',
        JPEG2000 = 'jpeg2000',
        JPEGLS = 'jpegls',
        JV = 'jv',
        KGV1 = 'kgv1',
        KMVC = 'kmvc',
        LAGARITH = 'lagarith',
        LJPEG = 'ljpeg',
        LOCO = 'loco',
        M101 = 'm101',
        MAD = 'mad',
        MAGICYUV = 'magicyuv',
        MDEC = 'mdec',
        MIMIC = 'mimic',
        MJPEGB = 'mjpegb',
        MMVIDEO = 'mmvideo',
        MOTIONPIXELS = 'motionpixels',
        MSA1 = 'msa1',
        MSCC = 'mscc',
        MSMPEG4V1 = 'msmpeg4v1',
        MSMPEG4V2 = 'msmpeg4v2',
        MSMPEG4V3 = 'msmpeg4v3',
        MSRLE = 'msrle',
        MSS1 = 'mss1',
        MSS2 = 'mss2',
        MSZH = 'mszh',
        MTS2 = 'mts2',
        MVC1 = 'mvc1',
        MVC2 = 'mvc2',
        MXPEG = 'mxpeg',
        NUV = 'nuv',
        PAF_VIDEO = 'paf_video',
        PAM = 'pam',
        PBM = 'pbm',
        PCX = 'pcx',
        PGM = 'pgm',
        PGMYUV = 'pgmyuv',
        PICTOR = 'pictor',
        PIXLET = 'pixlet',
        PNG = 'png',
        PPM = 'ppm',
        PRORES = 'prores',
        PSD = 'psd',
        PTX = 'ptx',
        QDRAW = 'qdraw',
        QPEG = 'qpeg',
        QTRLE = 'qtrle',
        R10K = 'r10k',
        R210 = 'r210',
        RAWVIDEO = 'rawvideo',
        RL2 = 'rl2',
        ROQ = 'roq',
        RPZA = 'rpza',
        RSCC = 'rscc',
        RV10 = 'rv10',
        RV20 = 'rv20',
        RV30 = 'rv30',
        RV40 = 'rv40',
        SANM = 'sanm',
        SCPR = 'scpr',
        SCREENPRESSO = 'screenpresso',
        SGI = 'sgi',
        SGIRLE = 'sgirle',
        SHEERVIDEO = 'sheervideo',
        SMACKVIDEO = 'smackvideo',
        SMC = 'smc',
        SMVJPEG = 'smvjpeg',
        SNOW = 'snow',
        SP5X = 'sp5x',
        SPEEDHQ = 'speedhq',
        SRGC = 'srgc',
        SUNRAST = 'sunrast',
        SVG = 'svg',
        SVQ1 = 'svq1',
        SVQ3 = 'svq3',
        TARGA = 'targa',
        TARGA_Y216 = 'targa_y216',
        TDSC = 'tdsc',
        TGQ = 'tgq',
        TGV = 'tgv',
        THP = 'thp',
        TIERTEXSEQVIDEO = 'tiertexseqvideo',
        TIFF = 'tiff',
        TMV = 'tmv',
        TQI = 'tqi',
        TRUEMOTION1 = 'truemotion1',
        TRUEMOTION2 = 'truemotion2',
        TRUEMOTION2RT = 'truemotion2rt',
        TSCC = 'tscc',
        TSCC2 = 'tscc2',
        TXD = 'txd',
        ULTI = 'ulti',
        UTVIDEO = 'utvideo',
        V210 = 'v210',
        V210X = 'v210x',
        V308 = 'v308',
        V408 = 'v408',
        V410 = 'v410',
        VB = 'vb',
        VBLE = 'vble',
        VCR1 = 'vcr1',
        VIXL = 'vixl',
        VMDVIDEO = 'vmdvideo',
        VMNC = 'vmnc',
        VP3 = 'vp3',
        VP5 = 'vp5',
        VP6 = 'vp6',
        VP6A = 'vp6a',
        VP6F = 'vp6f',
        VP7 = 'vp7',
        WEBP = 'webp',
        WMV3IMAGE = 'wmv3image',
        WNV1 = 'wnv1',
        WRAPPED_AVFRAME = 'wrapped_avframe',
        WS_VQA = 'ws_vqa',
        XAN_WC3 = 'xan_wc3',
        XAN_WC4 = 'xan_wc4',
        XBIN = 'xbin',
        XBM = 'xbm',
        XFACE = 'xface',
        XPM = 'xpm',
        XWD = 'xwd',
        Y41P = 'y41p',
        YLC = 'ylc',
        YOP = 'yop',
        YUV4 = 'yuv4',
        ZEROCODEC = 'zerocodec',
        ZLIB = 'zlib',
        ZMBV = 'zmbv',
    }
    export enum Direction {
        ENCODER = 'Encoder',
        DECODER = 'Decoder',
    }
    export enum SecondaryFramework {
        UNKNOWN = 'Unknown',
        NONE = 'None',
        AMD_AMF = 'AmdAmf',
        MEDIA_CODEC = 'MediaCodec',
        NV_ENC_DEC = 'NvEncDec',
        OPEN_MAX = 'OpenMax',
        QUICK_SYNC = 'QuickSync',
        VA_API = 'VaApi',
        V4L2 = 'V4L2',
        DX_VA = 'DxVa',
        D3D11VA = 'D3d11va',
        VIDEO_TOOLBOX = 'VideoToolbox',
    }
}

